---
name: bonnie++

instance_groups:
- name: bonnie++
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default

releases:
- name: bonnie++
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
